name: Frontend linter pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./client

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn eslint . --ext .js,.jsx,.ts,.tsx